### PR TITLE
CAW-478: Removed wrapping p tag from body as body has html tags in it an...

### PR DESCRIPTION
**Pull request by sherakama**
...d prefixed css ids with faq as number ids are invalid

### CODE REVIEW

**Comment by sherakama** [comment]
I have also added the collapse class by default as that is what they start as.

**Comment by sherakama** [comment]
@cjwest, please review.

**Comment by cjwest** [comment]
Looks good!

**Comment by cjwest** [comment]
How do I get the Readme to list items? 

https://github.com/SU-SWS/stanford_faq/blob/7.x-4.x-dev/README.md 

## Caryl 

Caryl J. Westerberg 
Web Producer, Stanford Web Services 
cjwest@stanford.edu 

swsblog.stanford.edu 

----- Original Message -----

**Pull request merged**
